name: rrule
description: Recurrence rule parsing & calculation as defined in the iCalendar RFC
version: 0.2.14
homepage: https://github.com/JonasWanke/rrule

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  intl: '>=0.17.0 <0.19.0'
  meta: ^1.3.0
  time: ^2.1.1

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1
  test: ^1.16.8
  # test_coverage: ^0.5.0
