name: rrule
description: Recurrence rule parsing & calculation as defined in the iCalendar RFC
version: 0.2.14
repository: https://github.com/JonasWanke/rrule

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  intl: '>=0.17.0 <0.19.0'
  meta: ^1.3.0
  time: ^2.1.1

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 4478bd902973c80b8ba1eb3754531542555f58ec
  test: ^1.16.8
